-- Run once in the Supabase SQL editor.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  subscription jsonb not null,
  updated_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

create table if not exists public.scheduled_reminders (
  user_id uuid not null references auth.users(id) on delete cascade,
  reminder_key text not null,
  fire_at timestamptz not null,
  title text not null,
  body text not null default '',
  silent boolean not null default false,
  target_url text not null default './index.html',
  delivered_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, reminder_key)
);

create index if not exists scheduled_reminders_due_idx
  on public.scheduled_reminders (fire_at)
  where delivered_at is null;

alter table public.push_subscriptions enable row level security;
alter table public.scheduled_reminders enable row level security;

drop policy if exists "users manage own push subscriptions" on public.push_subscriptions;
create policy "users manage own push subscriptions" on public.push_subscriptions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users manage own reminders" on public.scheduled_reminders;
create policy "users manage own reminders" on public.scheduled_reminders
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
